# Generated by Django 5.0.2 on 2024-11-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_message_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='connection',
        ),
    ]
