# Generated by Django 5.1.3 on 2024-11-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_alter_connection_astronaut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messsage',
            field=models.TextField(default='hello!'),
            preserve_default=False,
        ),
    ]
